package project5myversion;
// gui
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class StudentDirectory extends javax.swing.JFrame implements Serializable
{
    // List<Person> person = new ArrayList<Person>();
    List<Student> student = new ArrayList<Student>();
    // ********************************************* getter and setter for student
    public List<Student> getStudent() {
        return student;
    }

    public void setStudent(List<Student> student) {
        this.student = student;
    }
    // ********************************************* getter and setter for student
    // ********************************************* getter and setter for person
    /*
    public List<Person> getPerson() {
        return person;
    }

    public void setPerson(List<Person> person) {
        this.person = person;
    }
    */
    // ********************************************* getter and setter for person 
    
    /*
    student.add(new Student(9834, "Rob", "Flenn", "10-05-1993", "GSU"));
    student.add(new Student(3421, "Jennifer", "Shin", "06-12-1990", "NYU"));
    student.add(new Student(8897, "Esther", "Cole", "03-05-1998", "MIT"));
    
    StudentDirectory directory = new StudentDirectory();
    directory.serialize(student, "src/project5myversion/StudentsList.dat");
    */
    
    
    //****************************************************** gui
    /**
     * Creates new form StudentDirectory
     */
    public StudentDirectory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        IDTextField1 = new javax.swing.JTextField();
        FirstNameTextField2 = new javax.swing.JTextField();
        LastNameTextField3 = new javax.swing.JTextField();
        DOBTextField4 = new javax.swing.JTextField();
        CollegeTextField5 = new javax.swing.JTextField();
        IDLabel1 = new javax.swing.JLabel();
        FirstNameLabel2 = new javax.swing.JLabel();
        LastNameLabel3 = new javax.swing.JLabel();
        DOBLabel4 = new javax.swing.JLabel();
        CollegeLabel5 = new javax.swing.JLabel();
        PreviousButton1 = new javax.swing.JButton();
        NextButton2 = new javax.swing.JButton();
        AppendButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        LoadjMenuItem1 = new javax.swing.JMenuItem();
        SavejMenuItem3 = new javax.swing.JMenuItem();
        ExitjMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Directory");

        IDLabel1.setText("ID");

        FirstNameLabel2.setText("First Name");

        LastNameLabel3.setText("Last Name");

        DOBLabel4.setText("Date of Birth");

        CollegeLabel5.setText("College");

        PreviousButton1.setText("Previous");
        PreviousButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButton1ActionPerformed(evt);
            }
        });

        NextButton2.setText("Next");
        NextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton2ActionPerformed(evt);
            }
        });

        AppendButton3.setText("Append");
        AppendButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppendButton3ActionPerformed(evt);
            }
        });

        jMenu2.setText("File");

        LoadjMenuItem1.setText("Load");
        LoadjMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadjMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(LoadjMenuItem1);

        SavejMenuItem3.setText("Save");
        SavejMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(SavejMenuItem3);

        ExitjMenuItem2.setText("Exit");
        ExitjMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(ExitjMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PreviousButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NextButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(AppendButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel1)
                            .addComponent(FirstNameLabel2)
                            .addComponent(LastNameLabel3)
                            .addComponent(DOBLabel4)
                            .addComponent(CollegeLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DOBTextField4)
                            .addComponent(LastNameTextField3)
                            .addComponent(FirstNameTextField2)
                            .addComponent(IDTextField1)
                            .addComponent(CollegeTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollegeLabel5)
                    .addComponent(CollegeTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousButton1)
                    .addComponent(NextButton2)
                    .addComponent(AppendButton3))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void PreviousButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        System.out.println("Previous");
    }                                               

    private void NextButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        System.out.println("Next");
    }                                           

    private void AppendButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        System.out.println("Append");
    }                                             

    private void ExitjMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // save first
        System.out.println("Exit");
        System.exit(0);
    }                                              

    private void LoadjMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        System.out.println("Load");
    }                                              

    private void SavejMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        System.out.println("Save");
    }                                              

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton AppendButton3;
    private javax.swing.JLabel CollegeLabel5;
    private javax.swing.JTextField CollegeTextField5;
    private javax.swing.JLabel DOBLabel4;
    private javax.swing.JTextField DOBTextField4;
    private javax.swing.JMenuItem ExitjMenuItem2;
    private javax.swing.JLabel FirstNameLabel2;
    private javax.swing.JTextField FirstNameTextField2;
    private javax.swing.JLabel IDLabel1;
    private javax.swing.JTextField IDTextField1;
    private javax.swing.JLabel LastNameLabel3;
    private javax.swing.JTextField LastNameTextField3;
    private javax.swing.JMenuItem LoadjMenuItem1;
    private javax.swing.JButton NextButton2;
    private javax.swing.JButton PreviousButton1;
    private javax.swing.JMenuItem SavejMenuItem3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration  
    // ****************************************************** gui
    
    // ****************************************************** test menu bar
    // create a menu bar
    /*
    JMenuBar mb = new JMenuBar();
    
    // add choices/items on menu bar, call it file
    JMenu file = new JMenu("File");
    
    // create item Load
    JMenuItem load = new JMenuItem("Load");
    // create item Save
    JMenuItem save = new JMenuItem("Save");  
    // create items Exit
    JMenuItem exit = new JMenuItem("Exit");
    
    
    
    // add file to the menu bar
    mb.add(file);
    // add the item to the file menu
    file.add(load);
    // add the item to the file menu
    file.add(save);
    // add the item to the file menu
    file.add(exit);

    
    
    f.setJMenuBar(mb);*/
    // ****************************************************** test menu bar
    
    
    // ****************************************************** serialize
    // serialize
    public void serialize (List<Person> pList, String fileName)
    {
        try (ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(fileName)))
        {
            out.writeObject(pList);
        }
        catch (IOException ex)
        {
            System.out.println("A problem occured during serialization");
            System.out.println(ex.getMessage());
        }
    }
    // ****************************************************** serialize
    // ****************************************************** deserialize
    // deserialize
    public List<Person> deserialize(String fileName)
    {
        List<Person> pList = null;
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream(fileName)))
        {
            // object input stream, dot operator
            // cast and assign 
            pList = (List<Person>) in.readObject();
        }
        catch (IOException | ClassNotFoundException ex)
        {
            System.out.printf("Deserialization error %s%n", fileName);
            System.out.println(ex.getMessage());
        }
        return pList;
    }
    // ****************************************************** deserialize
    // ****************************************************** loading method
    /*
    public loadList
    {
        int i=0;
        for (person p: peopleHolder){
            p.setName("newName" + i++);
        }
        
    }
    */
    // ****************************************************** loading method
}


