/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project5myversionnetbeans;

/**
 *
 * @author michaeldang
 */
public class StudentDirectory extends javax.swing.JFrame {

    /**
     * Creates new form StudentDirectory
     */
    public StudentDirectory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        IDTextField1 = new javax.swing.JTextField();
        FirstNameTextField2 = new javax.swing.JTextField();
        LastNameTextField3 = new javax.swing.JTextField();
        DOBTextField4 = new javax.swing.JTextField();
        CollegeTextField5 = new javax.swing.JTextField();
        IDLabel1 = new javax.swing.JLabel();
        FirstNameLabel2 = new javax.swing.JLabel();
        LastNameLabel3 = new javax.swing.JLabel();
        DOBLabel4 = new javax.swing.JLabel();
        CollegeLabel5 = new javax.swing.JLabel();
        PreviousButton1 = new javax.swing.JButton();
        NextButton2 = new javax.swing.JButton();
        AppendButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Directory");

        IDLabel1.setText("ID");

        FirstNameLabel2.setText("First Name");

        LastNameLabel3.setText("Last Name");

        DOBLabel4.setText("Date of Birth");

        CollegeLabel5.setText("College");

        PreviousButton1.setText("Previous");
        PreviousButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButton1ActionPerformed(evt);
            }
        });

        NextButton2.setText("Next");
        NextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButton2ActionPerformed(evt);
            }
        });

        AppendButton3.setText("Append");
        AppendButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppendButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel1)
                            .addComponent(FirstNameLabel2)
                            .addComponent(LastNameLabel3)
                            .addComponent(DOBLabel4)
                            .addComponent(CollegeLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DOBTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(LastNameTextField3)
                            .addComponent(FirstNameTextField2)
                            .addComponent(IDTextField1)
                            .addComponent(CollegeTextField5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PreviousButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NextButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(AppendButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CollegeLabel5)
                    .addComponent(CollegeTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousButton1)
                    .addComponent(NextButton2)
                    .addComponent(AppendButton3))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    private void PreviousButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void NextButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void AppendButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    
    // **************************************************************** Taking Out MAIN
    
    
    
    
    
    // **************************************************************** Taking Out MAIN
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton AppendButton3;
    private javax.swing.JLabel CollegeLabel5;
    private javax.swing.JTextField CollegeTextField5;
    private javax.swing.JLabel DOBLabel4;
    private javax.swing.JTextField DOBTextField4;
    private javax.swing.JLabel FirstNameLabel2;
    private javax.swing.JTextField FirstNameTextField2;
    private javax.swing.JLabel IDLabel1;
    private javax.swing.JTextField IDTextField1;
    private javax.swing.JLabel LastNameLabel3;
    private javax.swing.JTextField LastNameTextField3;
    private javax.swing.JButton NextButton2;
    private javax.swing.JButton PreviousButton1;
    // End of variables declaration                   
}